server:
  address: "xellar.ru:8080"

agent:
  endpoint: "xellar.ru:8080"
  timeout: 10s
  poll_interval: 2s
  update_per_iteration: 5

metrics:
  - name: Xellar
    type: gauge
    view: default

  - name: BuckHashSys
    type: gauge
    view: runtime